version: '3.8'

services:
  grok-openai-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: grok-openai-api:latest
    container_name: grok-openai-api
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TZ=${TZ:-UTC}
      - PYTHONOPTIMIZE=${PYTHONOPTIMIZE:-1}
      - PORT=${PORT:-5000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - WORKERS=${WORKERS:-4}
      - API_CONNECT_TIMEOUT=${API_CONNECT_TIMEOUT:-10.0}
      - API_READ_TIMEOUT=${API_READ_TIMEOUT:-30.0}
      - DOWNLOAD_CONNECT_TIMEOUT=${DOWNLOAD_CONNECT_TIMEOUT:-5.0}
      - DOWNLOAD_READ_TIMEOUT=${DOWNLOAD_READ_TIMEOUT:-10.0}
      - RETRY_COUNT=${RETRY_COUNT:-2}
      - RETRY_BACKOFF=${RETRY_BACKOFF:-1.5}
      - POOL_CONNECTIONS=${POOL_CONNECTIONS:-10}
      - POOL_MAXSIZE=${POOL_MAXSIZE:-20}
      - MODEL_CACHE_SIZE=${MODEL_CACHE_SIZE:-100}
      - STREAM_BUFFER_SIZE=${STREAM_BUFFER_SIZE:-10}
      - DEFAULT_GROK_MODEL=${DEFAULT_GROK_MODEL:-grok-3}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/"]
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-10s}
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-2}'
          memory: ${MEMORY_LIMIT:-1G}